### ISSUE TITLE
Incorrect ICTS Shuttle timings

### ISSUE THREAD

**Issue by pvnkmrksk** [NCBSinfo/NCBSinfo#17]
I am not sure what is correct. The ICTS shuttle timings based on this https://www.icts.res.in/media/uploads/MediaLibrary/icts-bus-schedule.pdf is very different from the one in the app. There are many round-off errors and missing items. Can this be checked and corrected?

**Comment by rohitsuratekar** [comment]
Oh , I was not aware of new schedule. I got current schedule from NCBS reception. It will be updated by tonight. Thanks.

**Comment by rohitsuratekar** [comment]
Changes implemented in #18 as well as new app is deployed with corrected timings.
