### ISSUE TITLE
Hippo is going to be RESTful i.e. you can query the database (part of it) for showing information on your app

### ISSUE THREAD

**Issue by dilawar** [NCBSinfo/NCBSinfo#33]
Hi
The next version of Hippo (https://github.com/dilawar/HippoIgnited) will support queries using urls. For example. To see the upcoming events one can open `https://ncbs.res.in/hippo/upcomingevents/10?token=xaad92uandkaWHATEVER` and it will show the ten events on the same day in JSON format.

If you want some information from Hippo, update this ticket; I'll prepare links for them. The new version should be up in few days.

**Comment by rohitsuratekar** [comment]
Sounds good! Events are one of the most wanted feature. However, will this be public API ? Instead of upcoming events, it will be useful to get events by providing date as a parameter.

**Comment by dilawar** [comment]
We'll. The user must login to hippo once. It will generate the token for them and return it to app. Further queries can be done with token.

Need to think a bit more about it. 

However events can be scrapped from Google Calendar but it only has the academic events.

⁣Sent from Blue ​

**Comment by rohitsuratekar** [comment]
If authentication flow is similar to OAuth2, I can easily implement it in current app framework. If not, then it is tricky. Nonetheless, I think public events are fine. It is better to get them in a json format than scrapping from google calendar. Let me know if this can be done.

**Comment by rohitsuratekar** [comment]
Releasing new app design without any event information. All cloud functions are removed from current app to support LTS version. Maybe in future NCBS will make some official app for the same. Thank for the suggestion and support :)
